spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
  flyway:
    enabled: false
tenants:
  datasources:
    vw:
      jdbcUrl: jdbc:mysql://localhost:3306/vw?useSSL=false&serverTimezone=UTC&useLegacyDateTimeCode=false
      driverClassName: com.mysql.cj.jdbc.Driver
      username: rouclec
      password: '@admin123'
    bmw:
      jdbcUrl: jdbc:mysql://localhost:3306/bmw?useSSL=false&serverTimezone=UTC&useLegacyDateTimeCode=false
      driverClassName: com.mysql.cj.jdbc.Driver
      username: rouclec
      password: '@admin123'
    ikorBankUser:
      jdbcUrl: jdbc:mysql://localhost:3306/ikorBankUser?useSSL=false&serverTimezone=UTC&useLegacyDateTimeCode=false
      driverClassName: com.mysql.cj.jdbc.Driver
      username: rouclec
      password: '@admin123'